# fly.toml app configuration file generated for sks on 2023-12-01T21:38:32-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sks"
primary_region = "ord"

[build]

[deploy]
  release_command = ".fly/release.sh"

[env]
  DATABASE_URL = "file://data/sqlite.db"
  MIGRATE_ON_BOOT = "true"
  PORT = "8910"
  REDWOOD_DISABLE_TELEMETRY = "1"

[[mounts]]
  source = "data"
  destination = "/data"
  auto_extend_size_threshold = 0

[[services]]
  processes = ["app"]
  http_checks = []
  internal_port = 8910
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"


#[http_service]
#  internal_port = 8910
#  force_https = true
#  auto_stop_machines = true
#  auto_start_machines = true
#  min_machines_running = 0
#  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[processes]
  app = ".fly/start.sh"
  cron = ".fly/cron.sh"
