# fly.toml app configuration file generated for sidekicksammy-com on 2024-05-24T20:08:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sidekicksammy-com'
primary_region = 'ord'

[build]

[deploy]
  release_command = '.fly/release.sh'

[env]
  DATABASE_URL = 'file://data/sqlite.db'
  MIGRATE_ON_BOOT = 'true'
  PORT = '8910'
  REDWOOD_DISABLE_TELEMETRY = '1'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8910
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
